
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - python2.7
      - python-numpy
      - python-virtualenv

r_packages:
  - devtools

install:
  - R -e 'devtools::install_deps(dep = TRUE)'
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow()'

