sudo: false

language: r
warnings_are_errors: false

os:
  - linux
  - osx

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - export PATH=$(perl -e 'print join(":", grep { !m{/opt/python/} } split /:/, $ENV{PATH})')
  - source travis_install.sh

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev

script: |-
  R CMD build .
  travis_wait 60 R CMD check tensorflow*tar.gz

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

env:
  - TENSORFLOW_TEST_EXAMPLES="1"
    R_GCTORTURE="25"
