sudo: required

language: r
warnings_are_errors: false

os:
  - linux
  - osx

dist: trusty

cache: packages

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  - source travis_install.sh

apt_packages:
  - libmagick++-dev
  - wget
  - libatlas3gf-base
  - libatlas-dev
  - python-joblib
  - libpython-dev

r_packages:
  - testthat

notifications:
  email:
    on_success: change
    on_failure: always 

env:
  - TENSORFLOW_TEST_EXAMPLES="1"
    R_GCTORTURE="25"
