
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false

env:
  global:
    - TENSORFLOW_TEST_EXAMPLES="1"

cache:
  packages: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.virtualenvs/r-tensorflow

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

addons:
  apt:
    packages:
      - python2.7
      - python-numpy
      - python-virtualenv

before_script:
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow()'


